# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.prime_factorization_result import PrimeFactorizationResult  # noqa: F401,E501
from swagger_server import util


class PrimeFactorization(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result: List[PrimeFactorizationResult]=None):  # noqa: E501
        """PrimeFactorization - a model defined in Swagger

        :param result: The result of this PrimeFactorization.  # noqa: E501
        :type result: List[PrimeFactorizationResult]
        """
        self.swagger_types = {
            'result': List[PrimeFactorizationResult]
        }

        self.attribute_map = {
            'result': 'result'
        }
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'PrimeFactorization':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PrimeFactorization of this PrimeFactorization.  # noqa: E501
        :rtype: PrimeFactorization
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> List[PrimeFactorizationResult]:
        """Gets the result of this PrimeFactorization.


        :return: The result of this PrimeFactorization.
        :rtype: List[PrimeFactorizationResult]
        """
        return self._result

    @result.setter
    def result(self, result: List[PrimeFactorizationResult]):
        """Sets the result of this PrimeFactorization.


        :param result: The result of this PrimeFactorization.
        :type result: List[PrimeFactorizationResult]
        """
        if result is None:
            raise ValueError("Invalid value for `result`, must not be `None`")  # noqa: E501

        self._result = result
