# coding: utf-8

# flake8: noqa
"""
    Prime Factorization API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.input_numbers import InputNumbers
from swagger_client.models.prime_factorization import PrimeFactorization
from swagger_client.models.prime_factorization_result import PrimeFactorizationResult
